Dogadane/Dogadane/Controllers/HomeController.cs
using System.Linq;
using System.Web.Mvc;
using Dogadane.Models;
using Dogadane.ViewModels;

namespace Dogadane.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            using (var cont = new ApplicationDbContext())
            {
                var model = new SearchIndexViewModel
                {
                    CategoryOptions = cont.Categories.AsNoTracking().OrderBy(c => c.Name).ToList()
                };
                return View(model);
            }
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Dogadane/Dogadane/Controllers/PayuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dogadane.Interfaces;
using Dogadane.Models.Payu;
using Dogadane.Services;
using Dogadane.Utils;

namespace Dogadane.Controllers
{
    public class PayuController : Controller
    {
        IOrderService _orderService = new OrderService(new OrderValidator());
        private string algorithm = "SHA-256";

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetSignature(OrderData orderData)
        {
            var signature = _orderService.CreateSignature(orderData, "cb83ef4311d9d8e7263dd5d2d4d2d617");
            var hashedOrderSignature = Helpers.CreateAndHashOrderSignature(signature, orderData.MerchantPosId, algorithm);

            return string.IsNullOrEmpty(hashedOrderSignature)
                ? Json("Invalid")
                : Json(hashedOrderSignature, JsonRequestBehavior.AllowGet);
        }
    }
}

Dogadane/Dogadane/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

@Html.ActionLink("PRZEJDŹ DO PAYU", "Index", "Payu")

Dogadane/Dogadane/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Dogadane/Dogadane/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Szukaj";
}
@using Microsoft.AspNet.Identity
@model Dogadane.ViewModels.SearchIndexViewModel

<div class="row dgd-main-search" style="margin-top: 10px">
    <div class="col-md-4 dgd-search-col">
        <div class="form-group">
            <select id="ddCategory" class="form-control" data-placeholder="Kategoria">
                @foreach (var option in Model.CategoryOptions)
                {
                    <option value="@option.Id">@option.Name</option>
                }
            </select>
        </div>
    </div>
    <div class="col-md-6 dgd-search-col">
        <div class="form-group">
            <input id="tbInput" type="text" class="form-control" placeholder="Fraza">
        </div>
    </div>
    <div class="col-md-2 dgd-search-col">
        <div class="form-group">
            <select id="ddRange" type="text" class="form-control" placeholder="Zakres km">
                <option value="1">1km</option>
                <option value="5">5km</option>
                <option value="10">10km</option>
                <option value="50">50km</option>
            </select>
        </div>
    </div>
</div>
<div id="badges" class="container">
    <div class="row dgd-bottom-badges">
        <div class="col-md-4" style="margin-left: -50px; margin-top: 20px;">
            <div class="form-group dgd-tut-img">
                <img src="~/Content/ImagesHome/tut1_360.png" />
            </div>
        </div>

        <div class="col-md-4" style="margin-top: 20px;">
            <div class="form-group">
                <div class="form-group dgd-tut-img">
                    <img src="~/Content/ImagesHome/tut2_360.png" />
                </div>
            </div>
        </div>

        <div class="col-md-4" style="margin-top: 20px;">
            <div class="form-group">
                <div class="form-group dgd-tut-img">
                    <img src="~/Content/ImagesHome/tut3_360.png" />
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div id="results">

    </div>
</div>

<div id="noRecords" style="display: none; text-align: center;" class="container">
    <h4>Brak wyników wyszukiwania</h4>
</div>
@section scripts
{
    <script>
        var delay = (function () {
            var timer = 0;
            return function (callback, ms) {
                clearTimeout(timer);
                timer = setTimeout(callback, ms);
            };
        })();

        $("#ddCategory")
            .change(function () {
                getResults();
            });

        $("#tbInput")
            .keyup(function () {
                delay(function () {
                    getResults();
                }, 500);
            });

        $("#ddRange")
            .change(function () {
                getResults();
            });

        function getResults() {
            $.get('/Offer/Search?categoryId=' +
                $("#ddCategory").val() +
                "&input=" +
                $("#tbInput").val() +
                "&range=" +
                $("#ddRange").val(),
                function (data) {

                    var template = '<div class="col-sm-3 dgd-offer-tile">' +
                        '<div class="dgd-offer-tile-image"><img src="https://placeimg.com/500/500/people" class="img-responsive"/></div>' +
                        '<div class="dgd-offer-tile-col"><div class="dgd-offer-tile-title">%TITLE%</div> <div class="dgd-offer-tile-skill"><b>Umiejętność:</b> %SKILL%</div></div>' +
                        '<div style="clear: both">' +
                        '<div class="dgd-offer-tile-desc">%DESC%</div>' +
                        '<div><button class="btn btn-success" style="position: absolute; bottom: 10px" onclick="details(%ID%)">Szczegóły</button></div>' +
                        '<div class="dgd-offer-tile-category">%CATEGORY%</div> </div>';
                    $("#results").html('');

                    if (data.length === 0) {
                        $("#noRecords").show();
                    } else {
                        $("#noRecords").hide();
                    }

                    for (var i = 0; i < data.length; i++) {
                        var current = data[i];
                        $("#results").append(template.replace('%TITLE%', current.Title).replace('%DESC%', current.Description).replace('%CATEGORY%', current.CategoryName).replace('%SKILL%', current.MainSkill).replace('%ID%', current.Id));
                    }
                });
        }


        function details(id) {
            window.location.href = '/Offer/Details?offerId=' + id;
            //$.ajax({
            //    url: "/Offer/Details",
            //    method: 'POST',
            //    data: {
            //        "OfferId": id
            //    },
            //    success: function (data) {
            //    }
            //});
        }
            getResults();
    </script>
}